# Generated by Django 5.1.2 on 2024-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_remove_users_password_users_email_users_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
