# Generated by Django 5.1.2 on 2024-10-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_remove_users_first_name_users_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
    ]
