# Generated by Django 5.1.2 on 2024-10-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_rename_name_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=128)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
